# -*- coding:utf_8 -*-



[mailexecutor]
#executor模块所用的字典

#读取最近多少秒内的，管理员发送的最新几条邮件
recent_time = 1500
latest_mail = 2

#此文件是用来记录创建时间,会被修改更新,但不会存入数据
tempfile = 'Temp.last.runtime.AsTfvZkYxbQlusH.tmp'

#命令与参数的分隔符
separator = " "



[mailexecutor.cmdlist]
#只有在列表中的命令才会执行。

cups = "systemctl status cups.service"
ls = "ls"

# 有参数的命令
dbus = "systemctl {args} dbus.service" 



[mailexecutor.cmdhelp]
'dbus'= "dbus start|stop|status 控制dbus服务"
cups = "cups 显示cups服务状态"


[mailexecutor.master]
#能够发布命令的邮箱，只有这些邮件发送的命令才会被接受
#执行结果也会返回以下所有邮箱
'李四' = '66461627@qq.com'
'王五' = 'ong@live.com'



[mailexecutor.mailhelper]
#executor模块中调用的mailhelper模块所用的字典
#也可以将其它mailhelper配置,以'mailhelper'为键名添加到executor字典中,再传给executor模块中的类

display_name = '张三' #此账号发件时显示的名字
account = 'gasdgddr@163.com'
password = 'dsSADVy8ewN7G8V'
smtphost = 'smtp.163.com'
smtpport = 465
imaphost = 'imap.163.com'
imapport = 993
#-----------------------------